### ISSUE TITLE
Documentation_2.1_typos

### ISSUE THREAD

**Issue by mateothom** [priviere/PPBstats#106]
- Two types of network are handle within PPstats => Two types of network are handled with PPBstats
- unipart networks where a node can be: => unipart network (rm: au singulier car c'est un type de réseau) where nodes are: (rm: je mettrais au pluriel car tu mets edges au pluriel aussi)
- a seed lot => seedlots (rm: idem)
- a location => locations (rm: idem)
- bipart network where a node can be a location or a germplasm => bipart network where nodes are locations and germplasms,  and edges indicates which germplasm is present/grown in which location

**Comment by priviere** [comment]
done in PR #112
