### ISSUE TITLE
data_agro_HA.RData' has magic number 'RDX3'

### ISSUE THREAD

**Issue by robinnoel** [priviere/PPBstats#140]
* installing to library '.../Documents/R/win-library/3.4'
* installing *source* package 'PPBstats' ...
** R
** data
*** moving datasets to lazyload DB
Warning: file 'data_agro_HA.RData' has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = envir) : 
  mauvais num�ro magique de restauration de fichier (le fichier est peut �tre corrompu) -- aucune donn�e charg�e
ERROR: lazydata failed for package 'PPBstats'
* removing '.../Documents/R/win-library/3.4/PPBstats'
In R CMD INSTALL

Exited with status 1.

**Comment by priviere** [comment]
what is your R version ?
According to check, R >= 3.5.0:
`
NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'PPBstats/data/data_agro_HA.RData'  'PPBstats/data/data_agro_LF.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'PPBstats/data/data_agro_SR_4.RData'
`
I will update DESCRIPTION file

**Comment by robinnoel** [comment]
It works! Thanks Peter River!

**Comment by priviere** [comment]
With pleasure Mr Christmas !
