### ISSUE TITLE
Error downloading vignette data

### ISSUE THREAD

**Issue by famuvie** [priviere/PPBstats#50]
When I `get.PPBsttats.data()` it downloads a bunch of 818-byte RData files, which are really plain text, all with the same HTML content:

```HTML
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dropbox - 403</title>
<link href="https://cfl.dropboxstatic.com/static/css/error.css" rel="stylesheet" type="text/css"/>
<link rel="shortcut icon" href="https://cfl.dropboxstatic.com/static/images/favicon.ico"/>

</head>
<body>
<div class="figure">
<img src="https://cfl.dropboxstatic.com/static/images/lockbox.png" alt="Error: 403"/>
</div>
<div id="errorbox">
<h1>Error (403)</h1>It seems you don't belong here! You should probably <b><a href="https://www.dropbox.com/login">sign in</a></b>. Check out our <a href="https://www.dropbox.com/help">Help Center</a> and <a href="https://forums.dropbox.com">forums</a> for help, or head back to <a href="https://www.dropbox.com/home">home</a>.
</div>

</body>
</html>
```

Which is, on the other hand, the same thing I get when I manually try to download a file directly from the dropbox:
https://dl.dropboxusercontent.com/s/6qvl515k5484zg4/comp.mu.RData

Either the files are no longer there, or they are not anymore publicly available.

**Comment by famuvie** [comment]
Assuming they are too large to be included with the package, may I suggest using GitHub's releases (or pages) as a way to distribute them, rather than dropbox?

**Comment by priviere** [comment]
I have fix it and commit, it was not the right name for RData
It is a good idea to use GitHub's releases (or pages) : I open a new issue to deal with that later (it is not a priority I guess)

**Comment by famuvie** [comment]
I keep having the same error :(

**Comment by priviere** [comment]
aie, I do not know where could be the problem ...
everything is here, so you can go on
https://www.dropbox.com/sh/6qvl515k5484zg4/AADZKkaM2XZvmr9e6l5aWxN2a?dl=0

**Comment by famuvie** [comment]
I can see the files from your link, but it does not work from PPBstats.
PPBstats uses a link of the form: 
https://dl.dropboxusercontent.com/s/6qvl515k5484zg4/c_m2_y1.RData
which gives the reported error for me.
Does this link work for you, in your computer?

**Comment by priviere** [comment]
`get.PPBsttats.data()` works on my computer when using this link.
Maybe we should not spend to much energie on this bug if we move to  GitHub's releases ? cf #51

**Comment by famuvie** [comment]
Yeah. We can go down that way. Would you make a release with a zip file?

**Comment by priviere** [comment]
Ok, I'll see how to do it. So I close this post and move to #51
